<?php

namespace App\Libraries;

use App\Model\SettingModel;
use CodeIgniter\Database\BaseConnection;
use Config\Cms;
use Config\Database;
use RuntimeException;

/**
 * First-run installation and automatic database upgrades (like WordPress's
 * install.php and "Database Update Required").
 *
 * Every schema change is a migration in App/Database/Migrations. The newest migration
 * version that has run is stored in the `db_version` setting; when a newer migration
 * file is deployed, the admin panel runs it automatically on the next request.
 */
class Installer
{
    /**
     * [type, message] shown once in the admin panel after an automatic upgrade.
     */
    public ?array $notice = null;

    public function __construct(private readonly Cms $config)
    {
    }

    public function isInstalled(): bool
    {
        return is_file($this->config->lockFile);
    }

    /**
     * Open a connection with the credentials entered on the install screen.
     *
     * @throws RuntimeException when the database cannot be reached
     */
    public function connect(array $db): BaseConnection
    {
        $connection = Database::connect([
            'DSN'      => '',
            'hostname' => $db['hostname'],
            'username' => $db['username'],
            'password' => $db['password'],
            'database' => $db['database'],
            'DBDriver' => 'MySQLi',
            'DBPrefix' => $db['prefix'],
            'port'     => (int) $db['port'],
            'charset'  => 'utf8mb4',
            'DBCollat' => 'utf8mb4_unicode_ci',
            'DBDebug'  => true,
        ], false);

        try {
            $connection->initialize();
        } catch (\Throwable $e) {
            throw new RuntimeException('Could not connect to the database: ' . $e->getMessage(), 0, $e);
        }

        return $connection;
    }

    /**
     * Run every pending migration and record the schema version.
     */
    public function migrate(?BaseConnection $db = null): void
    {
        $runner = service('migrations', null, $db, false);
        $runner->setNamespace(APP_NAMESPACE);

        if (! $runner->latest()) {
            throw new RuntimeException('データベースのマイグレーションに失敗しました。');
        }

        $settings = $db ? new SettingModel($db) : model(SettingModel::class);
        $settings->put('db_version', $this->latestMigrationVersion());
    }

    /**
     * True when a migration file is newer than the schema version in the database.
     */
    public function needsUpgrade(): bool
    {
        return $this->latestMigrationVersion() > (string) setting('db_version', '0');
    }

    /**
     * Version (timestamp prefix) of the newest migration file on disk.
     */
    public function latestMigrationVersion(): string
    {
        $files = glob(APPPATH . 'Database/Migrations/*_*.php') ?: [];
        $latest = '0';

        foreach ($files as $file) {
            $version = preg_replace('/\D/', '', strstr(basename($file), '_', true));
            $latest  = max($latest, $version);
        }

        return $latest;
    }

    /**
     * Contents of the .env file: .env.example with this site's values filled in
     * (database, URL, names, and a new random encryption key).
     */
    public function envContents(array $db, string $baseURL, string $appName, string $adminEmail): string
    {
        $values = [
            'CI_ENVIRONMENT'             => 'production',
            'app.baseURL'                => $baseURL,
            'cms.appName'                => $appName,
            'cms.adminEmail'             => $adminEmail,
            'database.default.hostname'  => $db['hostname'],
            'database.default.database'  => $db['database'],
            'database.default.username'  => $db['username'],
            'database.default.password'  => $db['password'],
            'database.default.DBPrefix'  => $db['prefix'],
            'database.default.port'      => (int) $db['port'],
            'encryption.key'             => 'hex2bin:' . bin2hex(random_bytes(32)),
            'email.fromEmail'            => $adminEmail,
            'email.fromName'             => $appName,
        ];

        return self::fillEnv(
            is_file($this->config->envTemplate) ? (string) file_get_contents($this->config->envTemplate) : '',
            $values,
            'Generated by the SurexCore installer on ' . date('Y-m-d H:i:s'),
        );
    }

    /**
     * Replace "key = value" lines of an .env template; keys missing from the template are appended.
     */
    public static function fillEnv(string $template, array $values, string $comment = ''): string
    {
        // Numbers, the environment name and hex2bin: keys are written unquoted (as CodeIgniter does).
        $quote = static fn ($v): string => is_int($v) || in_array($v, ['production', 'development'], true) || str_starts_with((string) $v, 'hex2bin:')
            ? (string) $v
            : "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], (string) $v) . "'";

        foreach ($values as $key => $value) {
            $line    = $key . ' = ' . $quote($value);
            $pattern = '/^#?[ \t]*' . preg_quote($key, '/') . '[ \t]*=.*$/m';

            $template = preg_match($pattern, $template)
                ? preg_replace_callback($pattern, static fn () => $line, $template, 1)
                : rtrim($template) . "\n" . $line . "\n";
        }

        return ($comment !== '' ? '# ' . $comment . "\n" : '') . $template;
    }

    /**
     * Checked before touching the database so a failed install leaves nothing behind.
     */
    public function canWriteEnv(): bool
    {
        $file = $this->config->envFile;

        return is_file($file) ? is_writable($file) : is_writable(dirname($file));
    }

    /**
     * Write .env and the lock file.
     */
    public function finish(string $envContents): void
    {
        if (file_put_contents($this->config->envFile, $envContents, LOCK_EX) === false) {
            throw new RuntimeException('.env ファイルを書き込めませんでした。');
        }
        @chmod($this->config->envFile, 0640);

        file_put_contents($this->config->lockFile, date(DATE_ATOM));
    }
}
